# Generated by Django 3.2.24 on 2024-02-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('NEW', 'Nuevo'), ('INPROGRESS', 'En Progreso'), ('INREVIEW', 'En Revisión'), ('COMPLETED', 'Completado')], default='NEW', max_length=20),
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
