version: '3'

services:
  db:
    image: postgres:13
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: db_task
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  web:
    build: .
#    entrypoint: /code/entrypoint.sh
#    command: python manage.py runserver 0.0.0.0:8000
    command: >
      /bin/bash -c "
      while !</dev/tcp/db/5432; do
        echo 'Waiting PostgreSQL...'
        sleep 1
      done;
      echo 'PostgreSQL Started';
      python manage.py runserver 0.0.0.0:8000;
      "
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/db_task
